version: '3.1'
services:
  crud-php:
    container_name: cont-appphp-ex
    image: angelsuarez1612/examendockerphp:v1
    restart: always
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: cont-mariadb-ex
      DB_NAME: appphp
    ports:
      - 8095:80
    depends_on:
      - db
  db:
    container_name: cont-mariadb-ex
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: appphp
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data_ex:/var/lib/mysql
volumes:
    mariadb_data_ex:
